name: personal_expenses
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.35.6"

dependencies:
  auto_route: 8.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  firebase_auth: ^5.4.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_hooks: ^0.20.3
  flutter_secure_storage: ^10.0.0
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.6
  internet_connection_checker_plus: ^2.9.1+2
  simple_biometric: ^0.1.1
  sqflite: ^2.4.2

dev_dependencies:
  auto_route_generator: 8.0.0
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7

flutter:
  uses-material-design: true
