name: personal_expenses
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.35.6"

dependencies:
  audioplayers: ^6.2.0
  auto_route: 8.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.20.3
  flutter_secure_storage: ^10.0.0
  freezed_annotation: ^2.4.1
  get_it: ^8.0.3
  hooks_riverpod: ^2.4.6
  intl: ^0.20.2
  json_annotation: ^4.8.1
  mobile_scanner: ^7.2.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  simple_biometric: ^0.1.1
  sqflite: ^2.4.2

dev_dependencies:
  auto_route_generator: 8.0.0
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/beep.mp3
    #Environment
    - .env.dev
    - .env.qa
    - .env
